sonar.organization=lorconksu
sonar.projectKey=lorconksu_aerodocs
sonar.projectName=AeroDocs

sonar.sources=hub,agent,web/src,proto
sonar.tests=hub,agent
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*.pb.go,**/node_modules/**,**/dist/**

sonar.go.coverage.reportPaths=coverage-hub.out,coverage-agent.out

sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
