#!/bin/bash
set -euo pipefail

# AeroDocs Agent Installer
# Usage: curl -sSL https://hub.example.com/install.sh | sudo bash -s -- --token <TOKEN> --hub <GRPC_ADDR>
# The --url flag is auto-generated by the Hub and points to the binary download base URL.

TOKEN=""
HUB=""
URL=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --token) TOKEN="$2"; shift 2 ;;
    --hub)   HUB="$2";   shift 2 ;;
    --url)   URL="$2";   shift 2 ;;
    *)       echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [ -z "$TOKEN" ] || [ -z "$HUB" ]; then
  echo "Usage: sudo bash install.sh --token <TOKEN> --hub <GRPC_ADDR>"
  echo "  --token   One-time registration token from Hub"
  echo "  --hub     Hub gRPC address (e.g., 10.0.1.5:9090)"
  exit 1
fi

# Detect OS and architecture
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ARCH="amd64" ;;
  aarch64) ARCH="arm64" ;;
  *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

if [ "$OS" != "linux" ]; then
  echo "Unsupported OS: $OS (only linux is supported)"
  exit 1
fi

# Build download URL
if [ -z "$URL" ]; then
  # Fallback: derive from hub address (assumes same host serves HTTP)
  HUB_HOST=$(echo "$HUB" | cut -d: -f1)
  URL="https://${HUB_HOST}"
fi
DOWNLOAD_URL="${URL}/install/${OS}/${ARCH}"

echo "==> Downloading AeroDocs Agent (${OS}-${ARCH})..."
curl -sSL "$DOWNLOAD_URL" -o /usr/local/bin/aerodocs-agent
chmod +x /usr/local/bin/aerodocs-agent

echo "==> Creating config directory..."
mkdir -p /etc/aerodocs

echo "==> Installing systemd service..."
cat > /etc/systemd/system/aerodocs-agent.service <<EOF
[Unit]
Description=AeroDocs Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/aerodocs-agent --hub ${HUB} --token ${TOKEN}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now aerodocs-agent

echo ""
echo "==> AeroDocs Agent installed and started!"
echo "    Service: systemctl status aerodocs-agent"
echo "    Logs:    journalctl -u aerodocs-agent -f"
